name: Publish to NuGet

on:
 release:
   types: [published]

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      
      - name: Publish
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: parsers/dotnet/Taml.NET/Taml.NET.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
